### ISSUE TITLE
User preference bug

### ISSUE THREAD

**Issue by angusmcleod** [angusmcleod/discourse-quick-messages#36]
The user interface setting is not showing up when the user selection setting is enabled. I think it's an incorrect variable name in the client. See if you can find it.

**Comment by ryanerwin** [comment]
@angusmcleod 

The problem is in `[show-quick-messages.js.es6](https://github.com/angusmcleod/discourse-quick-messages/blob/badge_based_access/assets/javascripts/discourse/connectors/user-preferences-interface/show-quick-messages.js.es6)` inside `shouldRender`.... 

```
export default {
  shouldRender(args, component) {
    return Discourse.SiteSettings.quick_messages_enabled &&
      Discourse.SiteSettings.quick_message_user_preference &&
      args.model.quick_messages_access
  }
}
```

The problem is that we don't have `User.quick_messages_access` anymore... But without it, I don't have access to the entire badge object... 

We can't use the value of `User.show_quick_messages` because setting the preference would then simultaneously toggle viewing the preference...

I tried to rewrite this function, but I don't have access to the user's entire badge list in this function... I could serialize all the users badges in `plugin.rb` but that seems to be more verbose than than re-adding `::User.quick_messages_access`.

Is there a way to do this in pure JavaScript that I'm overlooking? Maybe there's a way I can grab the promise output in this function (but then, is it good practice to replicate the badge checking logic here and plugin.rb?) 

Please advise on how you suggest handling this?

We could drop the check on `::User.quick_messages_access`, but then people who don't even have permission to access that feature would still have the preference for it, which would be somewhat confusing...

**Comment by ryanerwin** [comment]
Sounds good. I'll rework it with `quick_message_access` in the morning.

**Comment by ryanerwin** [comment]
I've checked this in, verified it's working when the preference is enabled and disabled

`https://github.com/angusmcleod/discourse-quick-messages/commit/72055f9c68b96197d65478f5f130670d3c938f7d`

**Comment by angusmcleod** [comment]
@ryanerwin Cool, make a PR into master and I'll review it.

**Comment by ryanerwin** [comment]
https://github.com/angusmcleod/discourse-quick-messages/pull/39
